# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://fferegrino.github.io/handy_dict/"

git_url = "https://github.com/fferegrino/handy_dict/tree/master/"

def custom_doc_links(name): return None
